apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 8080
      targetPort: {{ .Values.backend.users.port }}
  type: ClusterIP
