apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: alb-webhook-selfsigned-issuer
  namespace: kube-system
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alb-webhook-cert
  namespace: kube-system
spec:
  commonName: aws-load-balancer-webhook.kube-system.svc
  dnsNames:
    - aws-load-balancer-webhook.kube-system.svc
  secretName: aws-load-balancer-webhook-tls
  issuerRef:
    name: alb-webhook-selfsigned-issuer
    kind: Issuer

